### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Make the minimal, safe changes required to convert the repo's code to be syntax compatible with both Python 2 and Python 3.  There may be other changes required to complete a port to Python 3 but this PR is a minimal, safe first step.

Run: [futurize --stage1 -w **/*.py](http://python-future.org/futurize_cheatsheet.html)
* See Stage 1: "safe" fixes http://python-future.org/automatic_conversion.html#stage-1-safe-fixes

### CODE REVIEW

**Comment by Marten4n6** [comment]
Thanks!
I agree the server side shouldn't be stuck using a legacy version of python.
Do you think we should drop python2 support in favor of python3?
Currently working on improving the infection logic for EvilOSX, after that I'll have a look at what's needed to move to python3.

**Comment by Marten4n6** [comment]
```
Traceback (most recent call last):
  File "server/server.py", line 10, in <module>
    from .model import *
ValueError: Attempted relative import in non-package
```

**Comment by cclauss** [comment]
Sorry... Remove the dot...  __from model import *__

**Comment by Marten4n6** [comment]
I don't see the point of merging this back to master since in the future the server side will fully switch to python3.

**Comment by cclauss** [comment]
The best approach is to get the codebase working in both Python 2 and Python 3 and then switch over.  This way if someone has trouble, they have two different versions of Python to run under.

**Pull request merged**
